"""Generate 02_riemann_demo.ipynb."""
from __future__ import annotations

import json
from pathlib import Path

NB_PATH = Path(__file__).with_name("02_riemann_demo.ipynb")

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Riemannian pipeline на `new_format_data`\n",
            "\n",
            "Демонстрация пайплайна для комиссии:\n",
            "\n",
            "- **Вход:** сырой ЭЭГ `18 × 200` (1 с @ 200 Гц)\n",
            "- **Ковариации:** Ledoit–Wolf (`lwf`)\n",
            "- **Проекция:** Riemann tangent space\n",
            "- **Классификатор:** Logistic Regression\n",
            "- **Split:** 80/20 по пациентам\n",
            "\n",
            "> Полный прогон на ~935k train-окнах занимает время; здесь — subsample 200k для быстрой демонстрации.\n",
            "> Сохранённые метрики full train: `splits/riemann_results_lr_full.json`.\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "%matplotlib inline\n",
            "import sys\n",
            "from pathlib import Path\n",
            "\n",
            "import matplotlib.pyplot as plt\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import seaborn as sns\n",
            "\n",
            "ROOT = Path('/Users/vspyatochkin/diploma_MAG')\n",
            "sys.path.insert(0, str(ROOT))\n",
            "\n",
            "from riemann_new_format.dataset import (\n",
            "    NewFormatDataset,\n",
            "    indices_for_patients,\n",
            "    labels_for_indices,\n",
            "    load_split,\n",
            "    subsample_train_indices,\n",
            ")\n",
            "from riemann_new_format.pipeline import (\n",
            "    build_riemann_pipeline,\n",
            "    evaluate_binary,\n",
            "    predict_in_batches,\n",
            ")\n",
            "\n",
            "DATA_DIR = ROOT / 'new_format_data'\n",
            "FIG_DIR = Path('figures')\n",
            "FIG_DIR.mkdir(exist_ok=True)\n",
            "\n",
            "sns.set_theme(style='whitegrid')\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "ds = NewFormatDataset(DATA_DIR)\n",
            "train_patients, test_patients = load_split(DATA_DIR)\n",
            "\n",
            "train_idx = indices_for_patients(ds.meta, train_patients)\n",
            "test_idx = indices_for_patients(ds.meta, test_patients)\n",
            "y_train_full = labels_for_indices(ds.meta, train_idx)\n",
            "y_test = labels_for_indices(ds.meta, test_idx)\n",
            "\n",
            "train_idx_fit = subsample_train_indices(\n",
            "    train_idx, y_train_full, neg_per_pos=5.0, max_samples=200_000,\n",
            ")\n",
            "y_train = labels_for_indices(ds.meta, train_idx_fit)\n",
            "\n",
            "print(f'Пациентов train/test: {len(train_patients)} / {len(test_patients)}')\n",
            "print(f'Train fit: {len(train_idx_fit):,} | DEPD {int(y_train.sum()):,} ({100*y_train.mean():.1f}%)')\n",
            "print(f'Test:      {len(test_idx):,} | DEPD {int(y_test.sum()):,} ({100*y_test.mean():.1f}%)')\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "X_train = ds.get_batch(train_idx_fit)\n",
            "model = build_riemann_pipeline(classifier='lr', cov_estimator='lwf')\n",
            "model.fit(X_train, y_train)\n",
            "\n",
            "y_pred = predict_in_batches(model, ds._raw, test_idx, batch_size=512)\n",
            "metrics = evaluate_binary(y_test, y_pred)\n",
            "\n",
            "metrics_df = pd.DataFrame([metrics]).T\n",
            "metrics_df.columns = ['value']\n",
            "display(metrics_df.loc[['f1', 'precision', 'recall', 'specificity', 'accuracy']])\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "cm = np.array([\n",
            "    [metrics['tp'], metrics['fn']],\n",
            "    [metrics['fp'], metrics['tn']],\n",
            "], dtype=int)\n",
            "\n",
            "fig, ax = plt.subplots(figsize=(4.5, 4))\n",
            "sns.heatmap(\n",
            "    cm, annot=True, fmt=',', cmap='Blues', cbar=False, ax=ax,\n",
            "    xticklabels=['Pred DEPD', 'Pred bg'],\n",
            "    yticklabels=['True DEPD', 'True bg'],\n",
            ")\n",
            "ax.set_title(f'Riemann LR (200k subsample)\\nF1={metrics[\"f1\"]:.3f}')\n",
            "plt.tight_layout()\n",
            "fig.savefig(FIG_DIR / '06_riemann_confusion_demo.png', bbox_inches='tight')\n",
            "plt.show()\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## Гибрид: Riemann + compact features\n",
            "\n",
            "Compact set: `spectral, sync, turbulence, mutual_info, correlation_dynamics` (87 признаков).\n",
        ],
    },
    {
        "cell_type": "code",
        "metadata": {},
        "source": [
            "from riemann_new_format.dataset import DEFAULT_FEATURE_NAMES\n",
            "from riemann_new_format.pipeline import HybridRiemannClassifier\n",
            "\n",
            "ds.load_features(DEFAULT_FEATURE_NAMES)\n",
            "X_train_feat = ds.get_features_batch(train_idx_fit)\n",
            "\n",
            "hybrid = HybridRiemannClassifier(classifier='lr', cov_estimator='lwf')\n",
            "hybrid.fit(X_train, y_train, X_feat=X_train_feat)\n",
            "y_pred_h = predict_in_batches(\n",
            "    hybrid, ds._raw, test_idx, batch_size=512,\n",
            "    get_features_batch=ds.get_features_batch,\n",
            ")\n",
            "metrics_h = evaluate_binary(y_test, y_pred_h)\n",
            "\n",
            "compare = pd.DataFrame({\n",
            "    'Riemann only': [metrics['f1'], metrics['recall'], metrics['precision']],\n",
            "    'Riemann + features': [metrics_h['f1'], metrics_h['recall'], metrics_h['precision']],\n",
            "}, index=['F1', 'Recall', 'Precision'])\n",
            "display(compare.style.format('{:.3f}'))\n",
        ],
        "outputs": [],
        "execution_count": None,
    },
]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "pygments_lexer": "ipython3"},
    },
    "cells": cells,
}

NB_PATH.write_text(json.dumps(nb, ensure_ascii=False, indent=1), encoding="utf-8")
print("Wrote", NB_PATH)
