# Все пути относительно каталога этого файла: pipeline/configs/

output_root: ../../processed_data

path_template: "{dataset}/{subject_id}/{session_date}/{preproc_id}"

datasets:
  - id: new_data
    root: ../../new_data
    recordings:
      - recording_id: ""
        subject_id: FA0183YC
        session_date: "2025-03-21"
        eeg_path: NKT/EEG2100/FA0183YC.EEG
        tags:
          site: NKT
          device: EEG2100
          patient_id: 12344


  - id: "00000000"
    root: ../../00000000
    recordings:
      - recording_id: ""
        subject_id: FA0183FS
        session_date: "2025-03-21"
        eeg_path: NKT/EEG2100/FA0183FS.EEG
        tags:
          site: archive_batch
          batch_id: "00000000"
          patient: 11111

preprocessing:
  - id: depd_intervals_v1
    kind: depd_intervals_csv
    params: {}

  - id: windows_2s_0p5hop
    kind: sliding_windows_index
    params:
      window_sec: 2.0
      overlap_sec: 1.5
      n_label_channels: 18
